### ISSUE TITLE
Windows - Failed to compile

### ISSUE THREAD

**Issue by rsrini7** [rust-lang/rustlings#255]
Failed to compile : parking_lot-0.8.0

error[E0658]: const fn is unstable (see issue #53555)

<img width="738" alt="2019-12-23 23_24_43-" src="https://user-images.githubusercontent.com/5178105/71372933-a4225380-25db-11ea-8b71-f7056c74fb68.png">

**Comment by fmoko** [comment]
What version is your `rustc` at? (check using `rustc --version`)

**Comment by rsrini7** [comment]
I was using 1.31.0 . Working fine after upgrading to 1.40.0. Thanks.
